---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
        msg: " {{ item }}ist sehr schmackhaft."
    loop:
      - Reisdorf
      - Früh
      - Gaffel
